services:
  backend:
    image: vishalbhatsoori/chess-backend:v1.0
    container_name: chess-backend-instance
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always
    pull_policy: always
